language: android
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.gradle

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-18
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
    - chmod +x ./gradlew
    - ./gradlew build